version: 2
updates:
  
  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    target-branch: "develop"
    directory: "/src"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
